##
# Root configuration file embedded in application, configurations can be overwritten with external yml file.
##
app:
  lesscss:
    useCache: false

spring:
  datasource:
    
    ##
    # H2 Configuration (uncomment to enable)
    ##
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password:
    
    ##
    # Mysql Configuration (uncomment to enable)
    ##
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://localhost:33306/data
    #username: user
    #password: changeit
    
#  jpa:
#    hibernate:
#      ddl-auto: validate
    
    
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
    
joinfaces:
  jsf:
    project-stage: development
#  primefaces:
#    theme: omega
    
server:
  error:
    includeException: true
    
logging:
  level:
    ROOT: INFO
    org.spring.security: INFO
    org.hibernate: INFO
    org.springframework.web: INFO
    liquibase: INFO
